---
title: 'Impact Analysis: Week 8, 2015'
author: "Tate Campbell"
date: "October 28, 2015"
output: pdf_document
---

#CASH GAME PLAYS



```{r, echo=FALSE, warning=FALSE, comment=NA}
impact <- function(pos){
  dir_name <- paste("~/sports_projects/Football/data/past_performance_data/", pos, "s", sep = "")
  setwd(dir_name)
  files <- list.files()
  n <- length(files)
  f5 <- read.csv(files[n])
  f4 <- read.csv(files[n-1])
  f3 <- read.csv(files[n-2])
  f2 <- read.csv(files[n-3])
  f1 <- read.csv(files[n-4])
  names(f5)[1] <- "name"
  names(f4)[1] <- "name"
  names(f3)[1] <- "name"
  names(f2)[1] <- "name"
  names(f1)[1] <- "name"
  num <- min(c(length(f5$name), length(f4$name), length(f3$name), length(f2$name), length(f1$name)))
  if (pos == "QB")
    num = num - 1
  df <- NULL
  for (i in 1:(num-1)){
    df$player[i] <- as.character(f5$name[i])
    df$w5[i] <- f5$Points[i]/(f5$Salary[i]/1000)
    c <- 1
    i4 <- which(as.character(f4$name) == df$player[i])
    i3 <- which(as.character(f3$name) == df$player[i])
    i2 <- which(as.character(f2$name) == df$player[i])
    i1 <- which(as.character(f1$name) == df$player[i])
    if (length(i4)){
      df$w4[i] <- f4$Points[i4]/(as.numeric(as.character(f4$Salary[i4]))/1000)
      c=c+1
    }
    if (length(i3)){
      df$w3[i] <- f3$Points[i3]/(as.numeric(as.character(f3$Salary[i3]))/1000)
      c=c+1
    }
    if (length(i2)){
      df$w2[i] <- f2$Points[i2]/(as.numeric(as.character(f2$Salary[i2]))/1000)
      c=c+1
    }
    if (length(i1)){
      df$w1[i] <- f1$Points[i1]/(as.numeric(as.character(f1$Salary[i1]))/1000)
      c=c+1
    } 
    
    df$avg_impact[i] <- mean(c(df$w1[i],df$w2[i],df$w3[i],df$w4[i],df$w5[i]), na.rm = TRUE)
    df$sd_impact[i] <- sd(c(df$w1[i],df$w2[i],df$w3[i],df$w4[i],df$w5[i]), na.rm = TRUE)
    df$LB_impact[i] <- df$avg_impact[i] - 1.645*df$sd_impact[i]
    df$UB_impact[i] <- df$avg_impact[i] + 1.645*df$sd_impact[i]
    df$N[i] <- c
  }
  df <- data.frame(df)
  df <- df[order(-df$LB_impact),]
  return(df[c("player", "avg_impact", "sd_impact", "LB_impact", "UB_impact", "N")])
}
```

##QBs

```{r, echo=FALSE, comment=NA, warning=FALSE}
impact("QB")
```

\newpage

##RBs

```{r, echo=FALSE, comment=NA, warning=FALSE}
impact("RB")
```

\newpage

##WRs

```{r ,echo=FALSE, comment=NA, warning=FALSE}
impact("WR")
```

\newpage

##TEs

```{r, echo=FALSE, comment=NA, warning=FALSE}
impact("TE")
```

\newpage

##DSTs

```{r, echo=FALSE, comment=NA, warning=FALSE}
impact("DST")
```



